services:
  # HA
  # zookeeper-flink:
  #   image: zookeeper:3.8
  #   container_name: zookeeper-flink
  #   ports:
  #     - "2182:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   volumes:
  #     - ./zookeeper-flink/data:/data
  #     - ./zookeeper-flink/datalog:/datalog
  #   restart: always

  jobmanager:
    image: flink:${FLINK_VERSION}
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager  
      - TZ=Asia/Seoul
    volumes:
      - ./checkpoints:/opt/flink/checkpoints
      - ./savepoints:/opt/flink/savepoints
      # - ./ha:/opt/flink/ha
      - ./job:/opt/flink-job/job
      - ./jars:/opt/flink/jars
      - ./conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./log:/opt/flink/log
    restart: always

  taskmanager:
    image: flink:${FLINK_VERSION}
    container_name: flink-taskmanager-1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TZ=Asia/Seoul
    restart: always
    volumes:
      - ./checkpoints:/opt/flink/checkpoints
      - ./savepoints:/opt/flink/savepoints
      - ./jars:/opt/flink/jars
      - ./conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
