version: '3'

services:
  namenode:
    container_name: namenode
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"  # Namenode Web UI
      - "9000:9000"  # HDFS
    volumes:
      - namenode:/hadoop/dfs/name
    restart: always
    

  datanode:
    container_name: datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode
    restart: always
    env_file:
      - ./hadoop.env
    volumes:
      - datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    depends_on:
      - namenode

  resourcemanager:
    container_name: resourcemanager
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    hostname: resourcemanager
    restart: always
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"  # Resource Manager Web UI
    environment:
      - SERVICE_PRECONDITION=namenode:9870 namenode:9000 datanode:9864
    depends_on:
      - namenode

  nodemanager:
    container_name: nodemanager
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    hostname: nodemanager
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088 namenode:9000 datanode:9864 namenode:9870
    depends_on:
      - resourcemanager

  historyserver:
    container_name: historyserver
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    hostname: historyserver
    restart: always
    volumes:
      - historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"  # History Server Web UI
    environment:
      - SERVICE_PRECONDITION=resourcemanager:8088 namenode:9000 datanode:9864 namenode:9870
    depends_on:
      - resourcemanager

volumes:
  namenode:
  datanode:
  historyserver:


networks:
  default:
      name: hadoop_network