services:
  # Flink
  jobmanager:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager  
      - taskmanager.numberOfTaskSlots=2
    volumes:
      - ./docker/job:/opt/flink/job

  taskmanager:
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager